Update format.yml

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -20,8 +20,8 @@ jobs:
         run: flutter pub get
 
       - name: Format code
-        run: flutter format --line-length 200 lib/ test/ example/
+        run: dart format --line-length 200 lib/ test/ example/
 
       - name: Check for changes
         run: |
-          git diff --exit-code || (echo "::error::Code formatting issues found. Run 'flutter format --line-length 200 lib/ test/ example/' to fix." && exit 1)
+          git diff --exit-code || (echo "::error::Code formatting issues found. Run 'dart format --line-length 200 lib/ test/ example/' to fix." && exit 1)
